
---
- name: Execute TSO COmmands on a Z/OS System
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  
  tasks:

    - block:
      - name: Run z/OS TSO command(s).
        ibm.ibm_zos_core.zos_tso_command:
          commands: 
            "{{ zos_tso_command.split('\n') | default(\"NOP\") }}"
        register: command

      always:
        - name: "Print results from command(s). Click on the output and go to the 'JSON' tab to show more output."
          debug:
            var: command.output